### ISSUE TITLE
Down resources

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#101]
- https://github.com/cidles/mindericobot. _Contactd @pbouda about it_
- http://www.ark.cs.cmu.edu/TurboParser/nasmith_models/kin-turbo-v1.0.tgz. _Linked to internet archive, Noah Smith moved to UWashington_
- [Gïelese](http://gielese.no) - A media learning application for South Saami, including images, sound and animation for learning basic phrases and core vocabulary. JavaScript application, playable on the web or via PhoneGap apps in Android or iOS. _Down. Emailed._

**Comment by pbouda** [comment]
I deleted the mindericobot, it was more a test how for Arduino bluetooth connections in the end, even out-dated. Was not related to Minderico.

**Comment by RichardLitt** [comment]
@pbouda Cool, thanks. Good to know!

**Comment by RichardLitt** [comment]
Will reopen if I get word back.
