### ISSUE TITLE
Add Kosovo resources

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#110]
http://www.flossk.org/en
# flossk on IRC.

**Comment by RichardLitt** [comment]
Contacted them on IRC. I didn't see anything on the https://github.com/flosskosova GitHub which seems relevant. Closing this for now, will add as needed.

**Comment by h4ck3rm1k3** [comment]
Howdy, Got the message.

**Comment by RichardLitt** [comment]
@h4ck3rm1k3 Awesome! If you've got any resources, can you point me to them or add them? :) Otherwise, thanks for acknowledging. 👋

**Comment by h4ck3rm1k3** [comment]
Feedback from team 

Spellchecking dictionaries here
http://www.shkenca.org/k6i/index.html

Slightly more useful keyboard layout
http://plisi.org/tastiera/

and

eSpeak has been good in almost language I have tried, including
Albanian.
English is of course the only one where it gets things very wrong.

The group's use of proprietary GitHub issue tracking is highly
inconvenient.
Fortunately, their resulting list of softwares is very accessible.

**Comment by h4ck3rm1k3** [comment]
we have a mailing list you can join general <general@lists.flossk.org>  https://lists.flossk.org/cgi-bin/mailman/listinfo

**Comment by h4ck3rm1k3** [comment]
My resources for albanian

1. sq.wikipedia.org
2. http://elsie.de/ robert elsie texts in cc
3. there are little albanian languages, in kosovo they speak Gege which is not the standard albanian
https://en.wikipedia.org/wiki/Ghegs
https://en.wikipedia.org/wiki/Gheg_Albanian
there is a tiny wiki for that https://incubator.wikimedia.org/wiki/Wp/aln/Faqja_kryesore

**Comment by RichardLitt** [comment]
Hey @h4ck3rm1k3, thank you so much! 

> The group's (RichardLitt/endangered-languages) use of proprietary GitHub issue tracking is highly
inconvenient.

Can you clarify what you meant by this?

**Comment by h4ck3rm1k3** [comment]
I think this was an stab at github being non -free software.

**Comment by RichardLitt** [comment]
Ah! I get that. I'm sorry it's inconvenient - the free service does work pretty well for a lot of people, but yes, this could also be on GitLab or on a website. FWIW I am more than happy to communicate by email and maintain it from there. 

Closing this, then. Thank you, again!
