### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#112]
> First, link quality is very heterogeneous: for example under "Massive Dictionary and Lexicography projects” you list things that only point to books (without the books themselves being downloadable) and also pages where you can actually get to lexicographic material (though often only at considerable difficulty).
> 
> Second, the pages and subpages are often dead — this is good to know at top level.
> 
> Third, and most important, adding Ethnologue codes (as you already do at the "Language Specific Projects” section, but not above) would make the material far more searchable.

**Comment by HughP** [comment]
Does number 2 above reference content in number one? or are they two separate comments?

On further reflection I recall that the content of the linked lexicography content is "open" as in it is accessible, not "open" as in "open data".

Re number three: we are not using Ethnologue codes. Whoever is using this terminology needs to get with the times and realize that no-one in their right mind today uses Ethnologue codes. They are SIO 639-3 codes.  There is a difference. Ethnologue Codes are deprecated. ISO 639-3 codes are not.

**Comment by RichardLitt** [comment]
They're too separate comments. 

We might want to separate open vs open. Terminology is confusing. 

Regarding Ethnologue, I think your phrasing is a little unfair. Maybe we can have a section explaining our code usage, too, and why Ethnologue // ISO // whatever standard.

**Comment by HughP** [comment]
The Ethnologue explains the history of the relationship of the codes used in it on this page: http://www.ethnologue.com/about/history-ethnologue 5th paragraph and following. Prior to the 15th edn. The Ethnologue use a set of code known as "Ethnologue codes". The 15th edn. and following (we are now in the 19th edn.) stopped using "Ethnologue codes" and started exclusively using ISO 639-3 codes.

**Comment by RichardLitt** [comment]
Cool. The person who gave me this feedback may have been using the term informally, and doubtless knew this. Using ISO codes for any language resource is probably the best way to go.

**Comment by HughP** [comment]
You'd bee surprised. There are some who out right don't know the difference - via willful ignorance. And there are others who use the term "Ethnologue codes" in a manner to indicate that they are dismissive of the Ethnologue and the ISO 639-3 standard. Its always surprising to me which details linguists choose to pay attention to.

**Comment by RichardLitt** [comment]
@HughP Maybe I should be a bit clearer; I am giving them the benefit of the doubt, because they may very well read _this issue_ and be on this list. It is 100% better to be kind and thoughtful than judgmental.

**Comment by RichardLitt** [comment]
Tasks:
- [ ] Remove dead pages
- [ ] Check "Massive Dictionary and Lexicography projects" section
- [ ] Remove an open data but not open source information from this list, or mark it appropriately.
- [ ] Add a section about ISO codes vs Ethnologue codes.
- [ ] Ensure that any languages have ISO codes attached.
