### ISSUE TITLE
Contact 7000.org

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#119]
http://7000.org/volunteer/

**Comment by HughP** [comment]
That site is weird. They claim that SIL International is partnering with them, but I have never heard anything about this from the SIL side.

**Comment by roedoejet** [comment]
I know Alexa who is the executive director. It's a very new group, so I'm sure she'd appreciate any contact/networking.

**Comment by RichardLitt** [comment]
@roedoejet I'd love to get in contact with her. She doesn't have an email on the site that I can tell. Can you send us a connecting email?

**Comment by roedoejet** [comment]
sent you her address :)

**Comment by roedoejet** [comment]
Oh, sorry, it's 5am in Shanghai and my reading was a bit fuzzy. I see you asked for a connecting email not her address. I'm actually en route to Hawaii for ICLDC and ComputEL-2 (Alexa will be there as well). I can send an introductory email between you when I get there.
