### ISSUE TITLE
Google Font - closed source?

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#120]
So, the google font is listed as Apache 2.0 licensed. But under closed source.... how is this possible? is this an error? I thought that fonts were non-compiled software and that if it is Apache 2.0 that it was open source... what am I missing?

**Comment by dowobeha** [comment]
https://github.com/googlei18n/noto-fonts

**Comment by RichardLitt** [comment]
Linked and moves. See https://github.com/RichardLitt/endangered-languages/commit/20e415c7eebe84b27c41ed0038bbbdb099b10364.
