### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#124]
This list needs one.

**Comment by RichardLitt** [comment]
👋 Hi all. Short licensing message here. 

I am overhauling this list at the moment (or at least closing all of the open issues), and one of the things I've done is add a Creative Commons Attribution Share-Alike 4.0 license. You can read the text of this license, [here](https://github.com/RichardLitt/endangered-languages/blob/master/LICENSE). 

I am pinging all of the contributors to note them about this, because I did not have a CLA enforced. From here on out, all contributions (commits, PRs, etc) will fall under this license. I am not 100% sure if this is legally correct, but I am going to state that, unless any of you have any issues with the CC license, I am going to view your contributions as also accepting of that license. 

**If you don't want a CC license, let me know.** Either here, or by email. I can listen to your concerns, and may remove your contributions. 

This thread will be locked and closed in two weeks, so that it can't be abused to ping you in the future. Sorry for the annoyance this may cause. Please give this comment a 👍 if you saw it and agree, instead of commenting, to keep notifications low.

cc @cesine @HughP @alvations @ReadmeCritic @rtxanson @xrotwang @eddersko @snomos @kscanne @waldyrious @roedoejet @0joshuaolson1 @DrDub @orthographic-pedant @katamaritaco  @arne-cl

**Comment by xrotwang** [comment]
:+1:

**Comment by snomos** [comment]
👍

Sjur

**Comment by RichardLitt** [comment]
Thank you, all. This list is now listed under a CC license. I am now also distributing it over npm, [here](https://www.npmjs.com/package/endangered-languages). 

If you have any questions or comments, additions or subtractions, please don't hesitate to reach out to me.
