### ISSUE TITLE
Add a Slack community

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#130]
It would be great to be able to build a community of developers working on endangered languages. I don't like email lists; they end up being very low priority for everyone involved, and quickly fill up an already cluttered inbox. Using this repository or the @LowResourceLanguages org doesn't work very well, as it's mostly about individual code bases. I want a place for usefully discussing best practices and asking questions. 

I think a Slack group could help here. What do you think? @HughP @cesine

**Comment by cesine** [comment]
i love the idea of having a way for us to chat more often, maybe even having weekly office hours where someone answers q. we would definitely be able to push small steps forward and include more folks who are also living busy lives. the benefits of slack is that it could be private, anyone can ask any question about any repo, public or private. but that is also its downside. sometimes questions are async, often asked years after they were first answered. something googleable would probably be best to help everyone in our community (present and future) i havent seen any slack archives pop up in my search results on google so im betting thats not a straightforward way to configure slack... i've used gitter before but it looks like its limited to twitter and github users (although we'd love to encourage others in the LRL community to be on github so this might be a blessing in disguise): https://www.quora.com/What-are-the-pros-and-cons-of-Gitter-vs-Slack

**Comment by RichardLitt** [comment]
I haven't seen a nice out-of-the-box solution for Slack archives. One of the things I think is a strength is that it is not persistent, really, for unpaid teams. You don't need to worry about people far in the future reading your content, which you do if you're in a Google Group or some more easily-archivable service. By getting rid of that pressure, people tend to open up a bit more, and you have a more vibrant community space. 

Gitter is good, but it is single stream - I haven't seen it work for multiple different conversations. I think that it is a viable alternative, but mostly that's good for talking about direct actions happening on the repository, and not for other issues. 

I'm more inclined to use Slack, because I think it's more likely to be a community place for getting people who may not interface with this repo as much.

**Comment by HughP** [comment]
Ive never gotten slack to work for me.

all the best,
- Hugh
via android from Northwest Nigeria

**Comment by RichardLitt** [comment]
I have created a Slack community. Please invite anyone you think might be interested in live chatting about this stuff!

https://join.slack.com/t/lowresourcelanguages/shared_invite/MjIwNDk3ODQxNDU4LTE1MDE1OTM1NjYtMTJkNGMyNzRjMQ
