### ISSUE TITLE
Igbo

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#137]
Some resources here: http://igbonlp.org/resources.php

**Comment by RichardLitt** [comment]
I am not sure if this is an open resource. While the tool output is open, the code itself is not open source without registering, and possibly being denied.  

> Please let us know about the research you are doing with the resources you are downloading. Please give us your feedback. Your opinion is very important to us.

Depends on how you view "open".

**Comment by RichardLitt** [comment]
According to the Open Source Definition from OSI, this is not open source. See [here](https://opensource.org/osd). This tool is available only to researches, and is not distributed with a license.  Resources are freely available for research purposes only.
