### ISSUE TITLE
Add in a Corpus Section

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#16]
[] Add Georgetown corpus http://corpling.uis.georgetown.edu/cqp/

**Comment by HughP** [comment]
What is the point here on corpus? This seems to me to be a separate list... from technology.

**Comment by RichardLitt** [comment]
Corpora are useful items, integral parts of the tooling process and debatably definable as technology in themselves. I don't see any issue with adding in open source corpora that might be useful to people using some of the tools in this list. I ought to signpost a corpus section with a brief description of why I added them, though.

**Comment by RichardLitt** [comment]
Actually, I think you're right @HughP. This would belong in a separate list. Corpora are not multifunctional in themselves, and not code-based. Good call. Thanks. 

If someone wants to make awesome-corpora or something, that would be cool, but there are probably other lists out there by better organizations.
