### ISSUE TITLE
Add Hunspell and subsidiary resources

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#18]
http://hlt.sztaki.hu/resources/

**Comment by HughP** [comment]
There is a designated pathway for moving FLEx data to hunspell dictionaries. Ask for more details on the FLEx google group.

**Comment by RichardLitt** [comment]
:+1: Will do.

**Comment by HughP** [comment]
http://nlp.stanford.edu/kirrkirr/dictionaries/xmldictionary.html
https://github.com/soshial/xdxf_makedict

**Comment by RichardLitt** [comment]
Cool. No idea what to do with that first link, though.

**Comment by HughP** [comment]
Yeah, I was half asleep when I posted that. It is a page deep in the documentation of KirrKirr http://nlp.stanford.edu/kirrkirr/ an application for visualizing lexical data. Not sure if the application itself is open source, as apposed to shareware as I did not see a repo attached to it. But the XML formats linked to above are more than likely open.

**Comment by RichardLitt** [comment]
Doesn't look like it. XML formats by themselves are not helpful, though, I think.
