### ISSUE TITLE
Make subsections

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#25]
Possibilities:
- standardizing orthography; viewing and comparing different transcriptions
- grammatical analysis of texts
- multimedia interlinear playing of recordings with free and detailed translation
- version control (a la GitHub)

From ILAT.

**Comment by cesine** [comment]
Not sure if this helps, but we compared tools using these sections/categories once upon a time, _some_ of these categories might be re-wordable into sections which might be help visitors find relevant libs or codebases that can be repurposed for endangered language work

![ad_hoc_ways_of_getting_field_work_done](https://cloud.githubusercontent.com/assets/196199/6282821/7c422f4c-b90d-11e4-91ab-49ef32c48a16.png)

DataOne also has a list of software that is commonly used for data management by research teams, but which may or may not be designed for use by endangered lang field teams.  @RichardLitt if you want to expand to these sorts of software, i can look do the triage to see which are open source http://www.dataone.org/all-software-tools?page=4

**Comment by HughP** [comment]
That is an interesting list... not because of the content, though that is interesting too, but because of the assumptions it reflects. Excited for tomorrow.

**Comment by RichardLitt** [comment]
That is a really awesome table. These categories strike me: 
 - Versioning
 - Praat
 - ELAN
 - Database management

Actually, a repository for all Praat scripts would be amazing. 

Of course DataOne has a list of software. I hadn't thought to use their resources. Would you mind traiging? We should prioritize language tools (aka, don't add Joomla! because it's really not relevant to under resourced languages).

**Comment by HughP** [comment]
You know, for CMS platforms (I use WordPress a lot) and their plugins It would be good if they would aggregate their UI languages. I mean I know people who do a lot of UI / .po translation files in under resourced languages. If these platforms would aggregate that would be awesome.

**Comment by RichardLitt** [comment]
I'm not actually sure what you mean by aggregate, there.

**Comment by RichardLitt** [comment]
There are subsections. Closing this as it is not highly actionable.
