### ISSUE TITLE
Look into Giellatekno again

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#27]
- link is outdated. [Better](http://giellatekno.uit.no/index.eng.html)
-  What they have: Resources (analysers, spellcheckers, intelligent dictionaries) for tens of indigenous languges in northern Eurasia and Northern America, and a ready-made setup for making the same for other languages as well.

[The direct link](http://giellatekno.uit.no/doc/lang/index.html)

The links to resources for end-users:
http://giellatekno.uit.no/smilang.eng.html
http://giellatekno.uit.no/all-lang.eng.html

Behind the curtain, for developers:
http://giellatekno.uit.no/doc/lang/index.html

**Comment by RichardLitt** [comment]
@rtxanson Maybe you could help here?

**Comment by rtxanson** [comment]
@RichardLitt Totally, what specifically do you want to know? 

I noticed the language code needs to change, currently `sma` is listed, this is south saami. There's a generic `smi` for Saami languages, though. You could list that, and the other ISO codes for languages in the family though.

**Comment by rtxanson** [comment]
Some more things. I may submit a pull request later, but for now I'm being lazy.

Links for the keyboards in major mobile app stores:

 * https://itunes.apple.com/us/app/sami-keyboards/id948386025?mt=8
 * https://play.google.com/store/apps/details?id=no.uit.giella.keyboards.Sami

For now all of these feature the following languages: 

 * `smn` Inari Sami, `smj` Julev/Lule Sami, `sme` Northern Sami, `sje` Pite Sami, `sms` Skolt Sami, `sma` South Sami; and then swedish, norwegian and finnish.

**Comment by HughP** [comment]
I have a Keyboard issue open #46. I wonder if we should double list things...

**Comment by RichardLitt** [comment]
The message above was basically in an email from Trosterud Trond, who seems to work on the project. I think perhaps just a better description would be good? Currently the [list](https://github.com/RichardLitt/endangered-languages#sami) is messed up, too. Links to the keyboards for those languages would be good, as would be adding in the language codes, if you could.

Not a heavy cleanup, just some help.

**Comment by HughP** [comment]
A few years ago Trosterud published a paper, which I have cited about keyboards and under-resourced languages. But there is a difference between tools which allow one to make keyboard layouts for languages and keyboard files for languages. Which kind of tool are we pursuing to add to the list?

**Comment by RichardLitt** [comment]
Ah, fair point. I wouldn't add specific keyboard files for a language here - extensible code only, if possible.

**Comment by HughP** [comment]
Extensible as a criteria, not exactly a safe way to look at the situation, because both sets of code are modifiable - extensible. In analogy, It would be saying, do we link to automobiles or automobile factories. Both can be modified. Different user groups are interested in different components for different reasons, and some user groups don't know which one they should be interested in or why.

**Comment by RichardLitt** [comment]
Well, nothing says we have to be an exhaustive list - but we can try. If you're happy adding both, I don't think it would hurt the list to have them. We'll discuss it on the call.

**Comment by RichardLitt** [comment]
Took another look. Giellatekno unfortunately uses a giant svn repository for all of their code, and their website is _very annoying_ to navigate. I wish they would invest in mirroring their content to GitHub, or to at least a more fine-grained model. At the moment, the documentation and the content are not in the same place, so it's a bit tough to link to things. I frankly don't really want to link to multiple points in their SVN repository, for each language, but it may be necessary if we're going to have coverage here. That's what others seem to do. For instance, this page from the [Alberta Language Technology Lab](http://altlab.artsrn.ualberta.ca/tools-applications/), which links to standalone demos on the site (are those really useful for people?), which you can then figure out how to get from the gielletkno svn if you want. 

For now, there are other resources I found through searching their site: 

- [ ] [@hfst](https://github.com/hfst)
- [ ] [@voikko](https://github.com/voikko)
- [ ] [@hunspell](https://github.com/hunspell) (_Might already be in here_).
- [ ] [@Divvun](https://github.com/divvun)
- [ ] [@TurkuNLP](https://github.com/TurkuNLP)
- [ ] [@UniversalDependencies](https://github.com/universaldependencies)
- [ ] [@estnltk](https://github.com/estnltk)

These should be added. I've added a link to Gielletkno in the `Other Organizations` category, which satisfies my need for it to be on this list, for now, so all that's left to do to close this issue is to add these other organizations. I don't really want to spam everyone with issues, and since adding them will be straightforward, I'll just leave this open until that's done.

**Comment by RichardLitt** [comment]
Closed. Opened #131 to include future assessments.

**Comment by HughP** [comment]
Do you have a valid email address for T.? Can you pm it to me? Ive tried to
reach him but no reply.

all the best,
- Hugh
via android from Northwest Nigeria

On Jul 27, 2017 14:38, "Richard Littauer" <notifications@github.com> wrote:

Closed #27 <https://github.com/RichardLitt/endangered-languages/issues/27>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/RichardLitt/endangered-languages/issues/27#event-1181773435>,
or mute the thread

**Comment by RichardLitt** [comment]
I don't. Sorry @HughP!
