### ISSUE TITLE
Add in flashcard programs

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#35]
Anki has already been added in #32.

Also: Memrise allows upload.

**Comment by HughP** [comment]
I did some research on options for this a about 6 months ago. Ping me in a few days again and I'll send you a gist.

**Comment by RichardLitt** [comment]
Cool, thanks. I'm not currently looking for a massive writeup, just a list of the available options.

**Comment by RichardLitt** [comment]
:pineapple:

**Comment by HughP** [comment]
Syntactically what does :pineapple: mean?

**Comment by RichardLitt** [comment]
:ping:

**Comment by HughP** [comment]
Here is one...  https://github.com/somelinguist/VocabLift

More to come, just putting this here for a place holder.

**Comment by RichardLitt** [comment]
@HughP Was that the gist? Do you have more?

**Comment by RichardLitt** [comment]
Ustadmobile isn't open source. Closing this for now; feel free to add more resources if you have them in a PR, @HughP.
