### ISSUE TITLE
Endangered Languages organization

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#36]
I've been thinking of opening up an organization for open source software to reflect this list. 

Instead of only forking projects, it would provide a place for people to upload projects that they don't want to upload to their personal accounts (for instance, in case they don't have one) and for mirroring SourceForge and other non-GitHub hosted code. We could also mirror SourceForge // other code ourselves, if the license on the product allows. It would be something like OpenSourceFieldLinguistics. 

What do you think? Does that sound like a good plan?

Possible drawbacks: 
* I don't know if the organization would be useful to other people. Than again, I don't know if this list itself is of much use. _Solution_: Do it first, then worry about wasted time.
* There is a potential for lots of stale code, unless I or someone else regularly goes around and fetches upstream and pulls down any new changes. I don't like this, at all. _Solution:_ Go around every now and then and fetch. Signpost accordingly. 
* People may not like mirroring sources, license allowing or not. To be honest, if it's open, than that's not really a problem. _Solution:_ Signpost accordingly. 
* Where is the line for what constitutes useful for endangered language revitalization and not just field linguists? Does any computer language repo count? _Solution:_ Use judgement. Over extend, don't under list.

**Comment by RichardLitt** [comment]
**Justification**

Currently, this repository is a list of links. This has some major drawbacks - first, link rot means it requires a deal of maintenance. Second, a lack of volunteers means I have to maintain PRs myself. Third, I can delete it, and we'd end up with stale repositories without up-to-date lists if forkers kept their version, unless they updated theirs frequently. I don't like this. 

An organization would stop link rot by allowing us to copy resources in themselves. It would promote stale code by needing maintenance in regards to fetching upstream versions - but, to be honest, this is still better than just a list, because at least the resource isn't gone, we have a copy of it. It would allow people to actively search the code on-site, as well, and for us to maintain a copy of resources that otherwise might go down if an institutional website or funding runs out. Finally, I wouldn't be the only maintainer, but I could more easily add people to help fork stuff.

**Comment by Lingomat** [comment]
Following Lauren's Tweet... this is an interesting issue when I've been thinking about lately. Hugh Paterson [made an astute observation](http://hugh.thejourneyler.org/2013/software-needs-for-a-language-documentation-project/) I think:

> “Many of these [linguistic] software development teams do not take the approach
> that potential software users coming to their website want to be oriented to how
> these software solutions work together to solve specific problems in the language 
> documentation problem space.”

So without wanting to pour cold water on anything, I wonder the extent of demand for a repository of somewhat orphaned software? Unless, of course, whomever produced the tools or is using the tools (and ideally a combination of both) is able to frame an entry for a tool in these terms.

I'll go a bit further. I think a shorter curated list of software with adequate context explaining how one might use the software is more useful than a long list of software without context. I suppose you could draw a parallel to a language archive with/without metadata :)

**Comment by RichardLitt** [comment]
You're, of course, spot on, and I've thought of these things before as well. To the first point, I'm not a software development team, and I'm not building tools - the documentation of the software isn't a task I'm taking on. All I'm trying to do is point users towards it. I think that orphaned software is better than no software, though, so I would like to save any software that is available for a specific language or for a specific task, if possible. I would point to the original makers, if they exist, in the repository Readme. 

A shorter, curated list isn't the point of this repository, necessarily. What I was looking for, here, was a way to know what is actually out there. Before I started this list, I had no idea that there was paradoxically so much and so little actually available - by creating the list, I know more now than I did before. 

The ultimate goal is not the list. It is useful for one of the aims - educating people about what resources are in fact out there, and providing an easily searchable reference to them. The ultimate goal is a resource - a book, website, or something similar - that can be used to take a language from nothing to something, and for broader awareness of OS resources and for better allocation (aka, more extensible) of funds towards language communities. The next step is to split the list up into categories, as I've included as an [issue here](https://github.com/RichardLitt/endangered-languages/issues/25). 

For now, though, some resources might be lost themselves. So, I'm thinking of building an organization. I think that is a separate issue than the points you raise, which I hope I've answered. Make sense?

**Comment by Lingomat** [comment]
I'm still a little unclear. The ultimate goal seems reasonable but it might help to clarify the audience?

Providing a list (of links to resources) serves the purpose of aiding the discovery of software tools in this space. It's not clear to me what is gained by hosting software, other than creating a degree of confusion as far as versions and potentially obfuscating what is current and what is abandonware. I'd argue link rot is generally a side effect and not the main problem itself. 

Is orphaned software really better than no software? Some sorts of tools are more resilient but there have of course been many arguments made about the dangers of obsolete software. Bird & Simons 2003 in the language space in particular.

**Comment by HughP** [comment]
@RichardLitt I'm not sure that your list is really going to take off. People need more than lists - they need relevance. If you are proposing something like [homebrew](https://github.com/Homebrew/homebrew) for linguistics software or PRAAT scripts or ELAN scripts, that might actually take off, because you would be creating an engagement point and a marketplace.  The ability to add new projects to a repo is something that LinguistList's software list never had. For some the http://lingtransoft.info/ website serves to pull diverse technology information together. So, I am not sure why you would's work with Doug Higby (site moderator) to be able to quickly add content to the site (perhaps even via gists or github lists). In general I think the linguistics community does need more than a list it needs a scientific script and data repo, where if I want to replicate a published phonetics experiment, I could go grab the same scripts used in that experiment and apply it to my own data.

@Lingomat All things considered, it is kinda funny to see my blog post cited... its great to see that people actually read that stuff :-)

**Comment by RichardLitt** [comment]
@Lingomat I've been thinking about how best to define my audience, too. I started this because there wasn't a list of open source resources available anywhere. I hadn't thought too far beyond that. I think of it as more of an index than an intelligent list, and I think because of that defining the audience for this list (as opposed to my wider aims) may not be too necessary. 

Hosting code serves the purpose of saving code that may otherwise be destroyed if the original resource is taken offline, and serves the purpose of having that code available on GitHub - a non-institutional repository that generally works well for the open source community. 

I don't think loss of knowledge is ever useful. I don't see any arguments about obsolete _software_ in Bird and Simmons 2003 - I do see arguments against obsolete proprietary formats, but that doesn't mean we should throw out the baby with the software. Some of the original algorithms, contexts, example data, etc, may be useful to someone in the future. We can't know a priori. 

@HughP I don't think you're understanding the purpose of the list, or possibly I wasn't clear enough that the organization I'm proposing making doesn't necessarily come from the same place as this list. This list is an index of available resources. It is not a meter of relevance, not homebrew, not GitHub. I don't have any valuable metrics in place to know what take off would even mean, and I don't suspect I will at any point in the future. The original point of this repository was to provide a list of open source technologies to do with language, so that I could know what is out there and highlight for other people that open source is important. If one person has learned something, than it is a success. Perhaps I'm confused as to what you mean by 'take off'. 

Something like homebrew for linguistics software, or Praat scripts, or ELAN scripts would be really useful. And it's something I've been debating making for years. The question I am trying to pose in this issue is: would it be useful to mirror code that may be in danger of dying in a GitHub organization? Would it be useful to put that code on GitHub? 

Some organizations, such as PLoS, are working right now on better scientific code repositories. I recently attended the Workshop for Sustainable Software in Science ([details](http://wssspe.researchcomputing.org.uk/wssspe2/)), where a lot of us talked about just this. I'm not sure trying to fix that problem is within the scope of my abilities at the moment. However, forking and mirroring repositories is. 

What do you guys think?

**Comment by RichardLitt** [comment]
Oh, and thanks so much for commenting here, both of you. :) I really appreciate this discussion!

**Comment by rtxanson** [comment]
If anyone would like to contribute to a homebrew for language technology stuff, feel free to join in here: https://github.com/rtxanson/language-technology. Take up discussion in issues there though.

**Comment by cesine** [comment]
I'm in the field right now, so I was kind of in the wrong time zone to chime in on this thread, but basically I think we should all meet in person! 

My 2-cents:  I'm worried that chatting via text might result in a debate when we all kind of have similar interests, but dissimilar background knowledge and experiences. 

Suggestion: Let's get modern! We should all meet virtually in an On Air Google Hangout, it looks like around the time that everyone was commenting is a good time! We can meet-minds better by simply introducing ourselves in a real time round table :) Anyone else who wants to come (I tagged some folks) can join us if they are available in that time slot, or watch the broadcast later when they have time.

Why:
* it sounds like everyone in this thread is pretty excited about open source for endangered languages
* Richards list helped us meet each other and find out that we all exist!
* `It would be something like OpenSourceFieldLinguistics.` actually, we really like what you @RichardLitt  have to say, and we've read your code, we might be able to just invite you to the OpenSourceFieldLinguistics advisory board and bring your perspective and project in :) @HughP  and @Lingomat  I haven't met you guys or your read your code before, so meeting would be a good opportunity to find out what your perspectives are :)
 * proof that that we are cool: 
  * our advisory board has endangered language field linguists who are academics, but also folks who have worked as language teachers, and phoneticians and/or lexicographers at software companies so we have a diverse positive perspective on software tools and creative repurposing of code/tools/approaches for language work. we'd love to welcome more open source-ers from github who we don't know from friends of friends. The board meets twice a year (not a lot of work load)
  * we have student interns and postdocs who can help maintain the PRs and documentation
  * we also have some open source-ers who don't need a day job who can mentor students and also provide man-power to help with to some of what you outlined. 
 * we have some funding to help devs spend more time on their open source hobby, especially if they have mouth(s) to feed :)
 * Did anyone see [Joel's presentation at ETI3](http://youtu.be/dwKUxd8jUuE?t=8m16s) where he talks about what the OpenSourceFieldLinguistics org is all about and who we are in the real world :) You can also meet our student interns and developers in [the user tutorials playlist](https://www.youtube.com/watch?v=4XrO8AhGNqo&list=PLUrH6CNxFDrMtraL8hTLbLsQwdw1117FT) and in the [dev playlist](https://www.youtube.com/playlist?list=PLUrH6CNxFDrO3zLHtHAMW-8u_v7TSvE-H)
 * If you like text, you can read our [CAML 2012 paper] (https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/docs/CAML/caml2012.pdf?raw=true) particularly section 2.2 for more about our approach to repurposing open source to address the challenges in building software for low-resource language users
 * its funny youmentioned him, @dhigby actually contacted @gretchenmcc to find the fielddb team in 2012 when the project was just beginning to see where we could share resources and technology/experience :) we have been working towards the goals and discussion in that meeting, and meetings with others (Emily Bender, Doug Troy, @stevenbird, @jcgood and some others we met at [ComputEL](http://www.acsu.buffalo.edu/~jcgood/ComputEL.html)  as we gain new interns and man hours so it would be fun to invite more githubers into those conversations

@RichardLitt  if you like this suggestion, and you know [how to make a google on air hangout](https://support.google.com/plus/answer/2553119?hl=en&ref_topic=2553242&rd=1), can you post the link to one here and schedule it for when you think is best? or i can probably do it for us if you haven't used it before...

**Comment by HughP** [comment]
I use hangouts all the time, Just let me know when and where. BTW: I'll be in Hawai'i here in a few weeks, if anyone else is going. Presentation on Keyboards and Archiving Lexicons.

**Comment by cesine** [comment]
@HughP awesome! i read some of your blog today, very cool. i think @jrwdunham will be there too, you guys should go to lunch together! 

http://icldc4.weebly.com/uploads/2/4/9/6/24963413/icldc4_papers_12_11_14.pdf

```
GARDEN LANAI ROOM
(3.2.4) LingSync: web-based software for language documentation
Joel Dunham • jrwdunham@gmail.com
The University of British Columbia
Jessica Coon • jessica.coon@mcgill.ca
McGill University
Alan Bale • alancbale@gmail.com
Concordia University
We present LingSync, a suite of open source web-based applications that facilitate collaborative
linguistic fieldwork and language documentation. The features of LingSync were designed by
theoretical linguists and people involved in language revitalization. The result is an exciting tool
that contributes to language documentation, revitalization, and linguistic analysis.
Topic area: Data management
```

**Comment by HughP** [comment]
I also have a poster session. @jrwdunham can you PM me... My "dance card" is filling up... :-)

**Comment by Lingomat** [comment]
Hello again, I'll also be in Hawai'i. 

```
(2.7.2) Towards Language Documentation 2.0: Imagining a crowdsourcing revolutionMat Bettinson • mat@plothatching.com
University of Melbourne
Crowdsourcing offers the potential to scale documentary activity beyond the confines of ‘expert’
linguistic resources. We argue that Web 2.0-like evolution in language documentation is
necessary and even inevitable. This has deep ramifications for the design of tools and methods
and forces us to re-evaluate a number of key assumptions.
Topic area: Enriching theory, practice, and application
HIBISCUS BALLROOM 2
```

Really looking forward to Hawai'i. Hangout sounds awesome, I'd love to know more about what you're doing. Lingsync has created a bit of buzz around here. I'm fascinated by OpenSourceFieldLinguistics.org in general. Particularly looping in the different array of stakeholders.

**Comment by RichardLitt** [comment]
I think having a virtual meeting is a good idea. I'm OK doing a video broadcast. Here's the link: https://plus.google.com/events/c6mrehiut1vt6lbng91esqochq8

Regarding a good date, does 2pm PST on Saturday work for everyone? If not, does anyone want to volunteer to make a doodle poll about it?

**Comment by HughP** [comment]
I am in for 2PM PST. BTW I am PST in Eugene, OR.

**Comment by RichardLitt** [comment]
Topics:

 - Language-specific code vs. more broadly applicable code (https://github.com/RichardLitt/endangered-languages/issues/27)
 - Mirroring Sourceforge, etc.
 - Stale code and forking GitHub projects
 - Curation
 - Beyond the list; education materials, etc.

Please suggest more if you have some. Would be good to have an attack plan.

**Comment by HughP** [comment]
* Are we middleware, that is, more details than what we offer should be on the sites where we link to, but then do we pass what we know off to other services, like OLAC?
* Who is our target audience?

**Comment by cesine** [comment]
sounds good :)

**Comment by jrwdunham** [comment]
@HughP if you still have some free time in Manoa, let me know. It would be great to chat. My schedule is still pretty open. Let me know what works for you.

**Comment by HughP** [comment]
@jrwdunham Let's totally do it. Dinner one night might be an option too. But I need a way to contact you. I have my phone, but if you are not a USA phone # then, that might not be an option... can we tall on the google call?

**Comment by RichardLitt** [comment]
Had a good chat with @cesine, and decided that we're going to go ahead and make an organization for mirroring dead code. If anyone would like to comment, I'll leave this issue open for a few days. Our discussion can be watched here: https://www.youtube.com/watch?v=WMToYUX_bX0&feature=youtu.be

**Comment by HughP** [comment]
SOO sorry guys. thanks for recording it.

**Comment by RichardLitt** [comment]
Happens, don't worry about it. Well done running, that's awesome. 

`Under resourced` is good, but I think `low resource` is better. That's what I've heard used the most. I used `endangered languages` at first because it is catchy. 

Mirroring is essentially the same as forking; you can only fork on GitHub, whereas mirroring is copying code from offsite. We'd be doing both. A bot would help keep code on GitHub from being stale pretty easy, and we could also do one to test off site. 

Exact name suggestions? I think github.com/LowResourceLanguages should work, but I think it's a bit long.

**Comment by HughP** [comment]
Well @RichardLitt, google each term first, because I get a lot of hits on `Under resourced languages' including the following:
* http://www.mica.edu.vn/sltu2014/
* http://www.lrec-conf.org/proceedings/lrec2014/workshops/LREC2014-Workshop-CCURL2014-Proceedings.pdf
* https://www.academia.edu/9519349/Automatic_Speech_Recognition_for_Under-resourced_Languages_A_Grapheme-based_Approach
* http://link.springer.com/chapter/10.1007%2F978-3-642-19644-7_50#page-1

**Comment by RichardLitt** [comment]
I didn't say it was more common, just that I'm more familiar with it. They're basically synonymous. (wow, I totally should have been at that LREC workshop). You'll notice the description for this repository: "A list of resources for conservation, development, and documentation of **endangered, minority, and low or under-resourced human languages**." That's how I dealt with it, before. I come from a CS and not a LangDoc background, although I think they're not as far apart as people think they are and I've done work in both camps.  On another note, Under Resourced Languages has an unfortunate acronym.

So...verdict?

**Comment by HughP** [comment]
URL very funny...

**Comment by cesine** [comment]
My vote is for `low resourced` languages with the tagline which Richard has **endangered, minority, and low or under-resourced human languages** i've heard people call them LRLs, so I tried googling that and found yet another option for you to consider :(

https://www.google.com.vn/search?espv=2&q=LRL+language&oq=LRL+language

About 472,000 results (0.32 seconds) 
Scholarly articles for less resourced languages
… of RBMT systems for less-resourced languages - ‎de ILARRAZA - Cited by 14
… speech recognition for under-resourced languages: … - ‎Le - Cited by 43
… of Semantic Relations for Less-Resourced Languages - ‎Nikulásdóttir - Cited by 7


```
Submissions for LTC 2013 - Language & Technology ...
www.ltc.amu.edu.pl/content.en.html
electronic language resources and tools; formalization of natural languages; parsing ..... "Less Resourced Languages, new technologies, new challenges and  ...
ISCA Special Interest Group: Speech and Language ...
www.isca-speech.org/iscaweb/index.php/sigs?layout=edit&id=122
By definition, a minority language has a smaller resource base than the major ... Turkey) "Language technology for normalisation of less-resourced languages",  ...
Proceedings of the Workshop on Language Technology for ...
aflat.org › Biblio
Jul 11, 2012 - Title, Proceedings of the Workshop on Language Technology for Normalisation of Less-Resourced Languages (SaLTMiL 8 - AfLaT2012).
[PDF]

A Micro Crowdsourcing Architecture to Localize Web Content
www.w3.org/International/multilingualweb/limerick/slides/wasala.pdf
A Micro Crowdsourcing Architecture to Localize. Web Content for Less-Resourced Languages. Asanka Wasala Chris Exton Ruvan Weerasinghe. Reinhard  ...
[PDF]Leaving Behind the Less-Resourced Status. The Case of ...
itreebank.marginalia.it/publications/Passarotti_SaLTMiL.pdf
by M Passarotti - ‎Cited by 4 - ‎Related articles
Thomisticus, Latin can still be considered as a less-resourced language. ... resources for less-resourced languages, showing that, although creating from scratch  ...
```

**Comment by HughP** [comment]
I'm down with a clear tagline.

**Comment by cesine** [comment]
I sent you both a hangout chat to your Google+ accounts to see if we want to say hi now :)

**Comment by rtxanson** [comment]
I'll try to have a listen to the chat a bit later today. One thing that comes to mind given the name issue, is we could still make an attempt at being googleable under other terms as well, no matter what the name ends up being. I'd also be all for setting up some sort of [Github-pages](https://pages.github.com/) repo so that we can perhaps capture a few more people searching for this kind of stuff with a simple front page, explanation of the rationale.

**Comment by RichardLitt** [comment]
Yeah, a GitHub pages front makes sense. We can do that.

**Comment by RichardLitt** [comment]
I've created a repository called LowResourceLanguages. As such, this issue can be closed. 

https://github.com/LowResourceLanguages/about

The first issue on that repository involves filling out the README with a description of the organization aims. Those can largely be copied from this issue.

**Comment by cesine** [comment]
I also added the tagline to the organization. I couldnt fit LRL in the description so I put it in the name but it might be confusing.

When i was searching for packages in #63  i couldn't find anything for LRL or low resource language or any combination  of key words I could think of, except on GitHub. Part of this is that package manager search engines are usually not very good, but part if it is also that "language" is so ambiguous when working with code repositories that we have little to no chance of finding a human language project. I think we could recommend to other devs who care about low resource languages to use the tag "LRL" on their projects and maybe this would help make their projects more discoverable through traditional package managers. (on a parallel with NLP which was very easy to find in all package managers and almost always constantly meant Natural Language Processing)


Now the project page looks like if you're not signed into github

<img width="998" alt="screen shot 2015-08-02 at 10 45 21 am" src="https://cloud.githubusercontent.com/assets/196199/9026612/b04ae7ae-3903-11e5-9a9f-cc73a6d2446f.png">

**Comment by RichardLitt** [comment]
Thanks @cesine. I would just remove 'human' and add in 'lrl' at the end. 

In the future, it might be better not to add comments to closed issues or PRs, as the discussion on closed PRs or issues is assumed to be over. Opening a new issue isn't a problem. :)

**Comment by RichardLitt** [comment]
Renamed repo. Closing this now.
