### ISSUE TITLE
General Resources list

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#39]
It seems that in the main list of general resources that you have conflated several categories.

Software really does cover a lot of issues. But does having CBOLD - a dictionary project actually belong in the same list as an android app?

Is there a way to tag entries so that they will be part of multiple sub-lists?

**Comment by RichardLitt** [comment]
I was using _General_  to mean _I haven't sorted these yet_. Ideally, nothing would really be in the general category. 

Tagging might be an option, but I'm not sure how it would be done best in a markdown file. At some point, this would just result in a worse version of OLAC. 

Do you have specific examples of issues where something could be in multiple categories?

**Comment by HughP** [comment]
Lexicography software could be in a category for Chrome "because it is on the chrome platform" or it could be under "lexicography utilities" - Just sent a pull request.

I am interested in what you mean by "worse version of OLAC".

**Comment by RichardLitt** [comment]
Ok, fair point. I've opened #42 to discuss list depth. I think that's a better place to discuss this. (In retrospect, could probably have used this issue, but I want to make sure that other people know where to discuss things, too). 

By 'worse version of OLAC' I mean that it would basically be a dumb version of a database. OLAC is a useful resource for finding resources in other languages, although I don't think it sorts by license.

**Comment by RichardLitt** [comment]
Closing this for now. Feel free to comment if needed. Just remembered the reason I opened a new issue is because I feel that this is an issue that affects the entire repo, not just the general list.
