### ISSUE TITLE
Some interesting things to add to lexicography

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#41]
There is another here: http://www.africananaphora.rutgers.edu/glossing-conventions-mainmenu-186

An ASL Dictionary http://www.lifeprint.com/asl101/topics/gloss.htm

In terms of linguists doing stuff with code, Michael Dunn wrote and maintains LexDB: https://bitbucket.org/evoling/lexdb 
Simon Greenhill wrote and maintains: the core architecture under http://transnewguinea.org/ and the ABVD.
Rod casali maintains the infrastructure for Comparalex: http://www.comparalex.org/index.php?page=stdlist&id=13
Sealang is independently maintained.
Other software tools (not FLEx-Wesay-Webonary) for dictionary building include: LEXUS, ViCoS, Protégé, FileMakerPro, toolbox, Lexique Pro

**Comment by HughP** [comment]
@RichardLitt If you want to assign this one to me, I'll take care of it after you resolve the pull request... It would be helpful if you were to clarify the categories you would like things to "fall into", then I can just add some stuff.

**Comment by RichardLitt** [comment]
Cool. 

Generally, I've been linking directly to the repository or code resource, or to the descriptive page. If we could follow that protocol, it would be good. I've added a paragraph about that, here: 8b0672655c1c1f94a958c1c6e540dd54733ac880

I don't know how I forgot about lexdb, I've known about that for a while. I can't assign you this issue unless you've got contribution access to this repo. I'll think about sharing access, I want to make sure we're all on the same page first. 

Regarding categories, I'm happy with whatever you suggest. We can always change categories later. I've left comments on that PR - it's not quite ready to merge in yet. Thanks!

**Comment by RichardLitt** [comment]
Closing this. Feel free to reopen later. For now, I'm considering this a stale issue. In scope, I'd like to keep this repository to actual code, not anything more than that.
