### ISSUE TITLE
List depth and tagging

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#42]
Currently, we have the list as a flat markdown document. However, this may not be ideal - a link may be better placed in several places, not just under one heading. This has been referenced in #39 and to an extent #25. 

This issue is for discussing possibilities to get around this. Some ideas:
 - We could have a flat list and tag links with keywords
 - We could move away from markdown and host this list on a separate website. This would allow us to have multidimensional lists, or to use a database tool. However, this may go against the initial goal of the repository itself - having an open source list that is easy to fork, on GitHub.
 - We could use the GitHub wiki. I don't like this - wiki's are hidden a lot of the time, and don't have the same easy of use as a markdown list.

**Comment by HughP** [comment]
I should have noted that if we wanted to avoid CMSes with SQL we could go one of the two following ways:
* http://paulhammant.com/blog/github-as-a-cms-to-end-cmses.html
* [jekyll](https://github.com/jekyll/jekyll)

**Comment by RichardLitt** [comment]
Yes. I use jekyll for my main site, burntfen.com. It's also hosted on GitHub. That might work. I've been maintaining endangered-languages in the style of awesome-* lists (see my other two main repos). That might be a good way to go -- if it is clearly still editable by anyone, and accessible.

**Comment by RichardLitt** [comment]
Knowing what I now know:
- Wiki is out of the question.
- Another website is too much overhead for me.
- Tagging links with keywords makes sense; will work on this if anyone wants. For now, I'm not interested. 

I am happy with the current implementation.
