### ISSUE TITLE
OLAC usefulness discussion

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#44]
Issue #39 started a discussion about the usefulness of OLAC. I wanted to pursue that a bit more. So I am opening up this issue. OLAC is merely an aggregator, so if licenses are sent to OLAC then it is because the sending institution chose to send it, not because OLAC prevents it. However, I am more generally interested in use case which OLAC users expect OLAC to perform but OLAC does not perform. 

As an FYI: I have been investigating the usefulness of OLAC from UX point of view: some preliminary [notes are here.](https://docs.google.com/document/d/1vfs96X-lXpk0uWsGlOUUVaB0YdMHTabG_d3cj2QjyBk/edit?usp=sharing)

**Comment by RichardLitt** [comment]
What is the actual question? How can this issue be closed?

**Comment by HughP** [comment]
You suggested in #39 that OLAC was not very useful. This issue can be resolved if you could elaborate more on what you mean by:
 1. OLAC - as in which part - what is OLAC to you (a protocol, a website, an organization, a project, etc.)
 2. useful - (for which use case)

**Comment by RichardLitt** [comment]
No, I don't think that is what I suggested; sorry if it came off that way. Here is what I said:

> By 'worse version of OLAC' I mean that it would basically be a dumb version of a database. OLAC is a useful resource for finding resources in other languages, although I don't think it sorts by license.

Sorting by license and being on GitHub are two major differentiators we have from OLAC, as well as the possibility of hosting our own versions of the code. I'm not experienced enough to be able to comment more than that, though, at the moment; I haven't used OLAC much.
