### ISSUE TITLE
ISO 639-3 intergration

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#45]
For the Language projects section do we want to add the ISO 639-3 code to the template?

**Comment by RichardLitt** [comment]
What do you mean - you mean specify which codes the tools are useful for?

**Comment by HughP** [comment]
Sorry no. I mean in the template when we talk about tools for specific languages as is mentioned in the linked merger https://github.com/OpenSourceFieldlinguistics/endangered-languages/commit/f12bab2afc11a1655d33436b632416f6f728dc8f 

I an suggesting that this data could be more easily integrated with other data if it were aligned via the ISO 639-3.

**Comment by RichardLitt** [comment]
I think using the ISO 639-3 would be better, particularly in the subject headers. Right now, the links are broken - I've reported this to GitHub, but I'm not sure what the solution would be for that. Let's replace them with the ISO 639-3 codes, and then add their non-roman names beneath the headings. What do you think?

**Comment by HughP** [comment]
Yeah, I see what you mean about broken links - it only happens on unicode non-ascii stuff looks to be the way that tocdoc works. I would personally just do english name and then a comment line below the ## link with something parseable like the following. But what ever we do it should be consistent. Perhaps we could create a copy-paste template based on locale data from unicode and host that template as a separate file.
## Arabic
_ara :: العربية_
* Some item 1
* Some item 2 etc

**Comment by RichardLitt** [comment]
GitHub as fixed this issue, so it works now - I just tested it on another branch. However, I think I like the current solution more, so let's just stay with it.
