### ISSUE TITLE
Keyboarding - Text input technology

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#46]
From time to time I might update this comment. I posted a few links to text input solutions below: 

https://github.com/tavultesoft/keymanweb
https://github.com/tavultesoft
https://github.com/Mottie/Keyboard
https://github.com/ratreya/Lipika_IME An Input Method Engine (IME) for phonetic transliteration with built-in support for all Indic Languages
OSX Ukelele 
Win: MSKLC
Linux:
i18n formats: https://docs.google.com/a/sil.org/document/d/1XSFyUKFGJr3lTv1mmoL4Pmk3RTJJapwYZ63pAkiIYvg/edit

Though I have another list growing here: https://github.com/HughP/MLKA/blob/master/ReferencesAndLinks.md#keyboard-layouts

**Comment by RichardLitt** [comment]
I think it might be smart to include keyboards links with their associated languages, and if they are more general to just include then in a keyboard section. I think information should be taken out of the issues as much as possible - these are to dos, and shouldn't have information that isn't reflected in the list.

**Comment by HughP** [comment]
This makes, sense and is basically an answer to the question I just asked in #27. I guess we should have a conversation about what are the categories of software which fit under each language.

**Comment by RichardLitt** [comment]
Ah, so that's what that meant. Hmm. I feel like posting everything possible about any minority language will eventually be unbearable - whereas any software that can be extended to other languages or similar language families or other sparse datasets is interesting. Something like a keyboard file doesn't seem to fit here, as much. Perhaps I should clarify the definitions of what should be here in the intro?

**Comment by HughP** [comment]
Yea, clarification would help, out of that clarification discussion we might birth a software-type taxonomy. did you get a PR request from me? I added a file to the repo.

**Comment by RichardLitt** [comment]
Cool. Do you want to tackle it, or me? 

I got it - I've been getting everything. I have a full time job on top of this, of course, so if I'm a little late in replying don't worry. :)

**Comment by HughP** [comment]
I can tackle it but I'll wait till after we have our meet up so that things are a bit clearer in terms of the direction we are going.

**Comment by RichardLitt** [comment]
I went through and added a keyboard section. Seems like it was relevant. Feel free to add more if you find any.
