### ISSUE TITLE
Lexical Tools in the LIFt Ecosystem

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#50]
Check out listing here: http://hugh.thejourneyler.org/2013/lexical-data-management-helps-with-sil-software/

**Comment by RichardLitt** [comment]
@HughP Do you want to see which of these resources should be added here?

**Comment by HughP** [comment]
Yes... That was my intent. Not all of those tools are on github as far as I know... My hold up is that I need to resolve several branches of this repo I am several ahead and several behind. I am also unclear on if we are using this repo or the organizational repo.

**Comment by RichardLitt** [comment]
Cool. As far as branches go:
- **master**: Main. Commit stuff to this.
- **white-paper**: This is for the paper. Don't merge this until we hear back from LREC.
- **terminology**: I'm not sure what this is. I'm guessing it was going to be a PR. 

I don't know what personal branches you have. 

This repo should be used for a generic list. If you are going to be copying over any repositories, use the Low Resource Languages repository.

**Comment by RichardLitt** [comment]
Hey @HughP  - any movement on this or the other two issues you're assigned?

**Comment by HughP** [comment]
None yet.  #fieldwork

all the best,
- Hugh
via android from Northwest Nigeria

**Comment by RichardLitt** [comment]
Ah, that's right! No worries then. I'll see what I can do.

**Comment by RichardLitt** [comment]
Didn't find any open source repositories which weren't already on this list. \o/
