### ISSUE TITLE
Text Glossing

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#52]
Text Glossing fits right next to segmentation tools and tagging tools: [I started a list of citations and stuff.](https://docs.google.com/a/sil.org/document/d/14TO3fgJHD8zfi2hnQt1ag9rFRxCgO8sQEz_P9h-IOTs/edit?usp=sharing)

**Comment by RichardLitt** [comment]
Cool. 

Thanks for all of these. Going to take some time to sort through.

**Comment by RichardLitt** [comment]
@HughP: It doesn't look like any of these are OSS. I'm going to close this. Feel free to add any tools for glossing if you know of any, though.
