### ISSUE TITLE
Add Natural language generation codebases

### ISSUE THREAD

**Issue by cesine** [RichardLitt/endangered-languages#60]
@drdub, 

@RichardLitt has been working on a list of codebases we can use for endangered language work.  if you have time, can you send a PR with some NLG codebases you like? if you think the tool would be hard to use with low-resource languages little data, and/or with non SVO word order and/or complex morphology, leave a small caveat.

**Comment by RichardLitt** [comment]
:+1:

**Comment by DrDub** [comment]
Sure, something like "NLG.md" ... ?

**Comment by RichardLitt** [comment]
Just a subsection in the main list is fine.

**Comment by cesine** [comment]
@DrDub ping ping :P

**Comment by RichardLitt** [comment]
Hey @DrDub and @cesine, closing this as it is stale. Reopen if you want to contribute! Thanks.

**Comment by DrDub** [comment]
Sorry, I actually didn't have any experience with low resource languages NLG. I bumped into the sample grammars of Inuit in OpenCCG and remembered about this bug. I just sent you a PR. Good luck!

**Comment by RichardLitt** [comment]
No worries! Thanks!

**Comment by cesine** [comment]
@DrDub  thanks thats awesome! i had a hack-together with a friend to generate text, we found a python library which we ported into a simple node library so i'll submit that one too
