### ISSUE TITLE
What to do with stuff about localization such as CLDR

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#65]
So are apps or libs which deal with CLDR data viable for this list?

https://github.com/twitter/twitter-cldr-rb

Here is another one on python: http://babel.pocoo.org/

**Comment by RichardLitt** [comment]
I'm going to say not to the general list. We could start another section for broadly applicable tools that would be helpful, but drawing the line will be increasingly hard.

**Comment by HughP** [comment]
I agree clear boundaries are needed. I do see a difference between apps which can use CLDR data and apps which with chew on language data like NLTK. Though it is not clear to me how to articulate this difference. And it does get fuzzy with keyboard layouts. We have sofar added keyboard tools for individual languages, but these data can also be encoded in CLDR so a tool that uses layouts via CLDR would not be included...

**Comment by RichardLitt** [comment]
I think being fuzzy is fine. We can judge when people PR. 

If anyone brings up CLDR, point them to this issue. Reopen as needed.
