### ISSUE TITLE
Save Google Code repositories

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#68]
Google Code is shutting down. If you know of any repositories listed here or in general which use Google Code, we should fork them for the LRL organization. This needs to be done soon.

**Comment by HughP** [comment]
Our current list includes two projects hosted on google code. I think best practice would be to get the current maintainers to move to github (in their own organization or LRL) and then follow them on github: 

* [Rosetta Pangloss](https://code.google.com/p/rosetta-pangloss/source/checkout) The Rosetta Project's Pangloss system
* [GaelSpell](https://code.google.com/p/gaelspell/) Sources for an Irish language spell checker

**Comment by RichardLitt** [comment]
Cool. My bandwidth is choked until Monday / Tuesday, will try to get to this then.

**Comment by RichardLitt** [comment]
Changed link to new exported Rosetta. Contacted @kscanne on Twitter, pinged him just now.

**Comment by RichardLitt** [comment]
Found his repositories. Closing this.
