### ISSUE TITLE
Word Creator

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#69]
http://billposer.org/Software/WordGenerator.html

**Comment by RichardLitt** [comment]
Looks fine to me. Add it in?

**Comment by RichardLitt** [comment]
Might want to host this as a LowResourceLanguages repository. It's GNUPL, so that's fine legally. 

Still going to keep this closed - I think at some point, once I'm out of issues, we should go back through this list and just start mirroring everything we can.
