### ISSUE TITLE
Linguistic Data in JSON

### ISSUE THREAD

**Issue by HughP** [RichardLitt/endangered-languages#70]
https://github.com/digitallinguistics

**Comment by RichardLitt** [comment]
Huh. I wonder what Daniel is up to!

**Comment by cesine** [comment]
me too :)  looks pretty cool! i left them some jasmine tests easter egg maybe we will find out more :)

**Comment by RichardLitt** [comment]
Closed in b9fb49d88f21d29cabb2bfa9bd91fe4b6aa52f69.
