### ISSUE TITLE
Help Darrick get his Ojibway app on github 

### ISSUE THREAD

**Issue by cesine** [RichardLitt/endangered-languages#75]
We found out about Darrick's work and his open source codebase from here: http://www.ethnosproject.org/open-source-native-language-app-code/

He has a github but we cant fork his project because its not pushed yet https://github.com/dbaxter/Ojibway-Language-App

This issue is to create a forkable mirror for Darrick's source code so that if devs find improvements maybe they can contribute back.

Image assets for the projects

![ios-simulator-screen-shot-2012-02-12-10 59 03-pm](https://cloud.githubusercontent.com/assets/196199/9023975/99c89300-3881-11e5-91b1-278907b8bdd8.png)
![ios-simulator-screen-shot-2012-02-12-10 58 19-pm](https://cloud.githubusercontent.com/assets/196199/9023978/99cc1e08-3881-11e5-8144-f0d26ac2e1e3.png)
![ios-simulator-screen-shot-2012-02-12-10 57 22-pm](https://cloud.githubusercontent.com/assets/196199/9023977/99cb28d6-3881-11e5-978a-f8a1242c463c.png)
![ios-simulator-screen-shot-2011-11-01-9 26 53-am](https://cloud.githubusercontent.com/assets/196199/9023976/99c9bbcc-3881-11e5-9296-3431b574bd9e.jpg)

![ojibway-app-android-iphone](https://cloud.githubusercontent.com/assets/196199/9023994/99139148-3882-11e5-9281-8d5d5535d2f8.jpg)

**Comment by cesine** [comment]
Repos are ready to be used:
https://github.com/LowResourceLanguages/Ojibway-iphone-app
https://github.com/LowResourceLanguages/OjibwayMap

Next step:
- [ ] add the links to the list

**Comment by RichardLitt** [comment]
Thanks!
