### ISSUE TITLE
FirstVoices apps

### ISSUE THREAD

**Issue by cesine** [RichardLitt/endangered-languages#76]
http://www.ethnosproject.org/firstvoices-chat-app-enables-indigenous-language-speakers-to-text-in-their-own-language/

It looks like the source code is not available. On the other hand, their website says it's impossible to make an Android version (which might have been true in 2011, but as an Android dev, I can say it true anymore).

This issue is to contact them when I have time to ask them if they are doing okay with the android side, and if they are interested in opening the source so they could get some help.... I tried figuring out who to contact, but the server for info@fpcc.ca is down http://fpcc.ca

---

First Peoples' Cultural Council is a leader in the development and deployment of technology-based solutions for Indigenous language reclamation and revitalization.

The wealth of language data uploaded by Indigenous community champions to FirstVoices.com is being repurposed in multiple dictionary and tutor apps like the ones listed below.

Secwepemc
Secwépemc app
Released: Jan 22, 2013  Xeni Gwet'in
Xeni Gwet'in app
Released: Jan 17, 2013  Nazko-Dakelh
Nazko-Dakelh app
Released: Jan 17, 2013  FirstVoices Chat
FirstVoices Chat app
Released: June 18, 2012
Users Guide [PDF]
Northern St̕'át̕'imcets app logo
Northern St̕'át̕'imcets app
Updated: Mar 22, 2012   Ktunaxa app logo
Ktunaxa app 
Released: Mar 14, 2012  Sliammon app logo
Sliammon app
Updated: Mar 14, 2012   Nisg̱a'a app logo
Nisg̱a'a app
Released: Jan 25, 2012
Ehattesaht app logo
Ehattesaht app
Released: Jan 18, 2012  Kwak̓wala app logo
Kwak̓wala app
Released: Dec 21, 2011  Skidegate Haida Language app logo
Skidegate Haida app
Released: Oct 27, 2011  SENĆOŦEN app logo
SENĆOŦEN app
Released: Sep 30, 2011
Halq'eméylem app logo
Halq'eméylem app
Released: Sep 30, 2011
FirstVoices Language Tutor is available from the FirstVoices Language Tutor Website. Enquiries welcome.

More apps coming soon...

Lil'wat

Apps for Android Devices?

The Android operating system doesn’t currently support the specialized characters needed to write in First Nations languages. When this situation changes, FirstVoices apps will be developed for both platforms.

<img width="1197" alt="screen shot 2015-08-01 at 7 42 01 pm" src="https://cloud.githubusercontent.com/assets/196199/9024047/0fbd26e4-3886-11e5-8cc1-ac59a8f3b5f6.png">

**Comment by RichardLitt** [comment]
@cesine Have you contacted them?

**Comment by roedoejet** [comment]
Hi all, just finding this repo now and it's great! To update this, I live a stone's throw away from where FirstVoices is based and am a linguist/developer. The FirstVoices apps are now having problems with iOS 10 and I've been building a new version with the Ionic Framework for both iOS and Android. Eventually all languages will be done with this platform but we're starting with Ucwalmícwts, Halq'eméylem and SENĆOŦEN.

**Comment by roedoejet** [comment]
I should also note that I'm making the app open-source and am also writing documentation for how to implement it with other languages.

**Comment by cesine** [comment]
Yay! That's great news keep us posted ;)

**Comment by RichardLitt** [comment]
Yeah! Totally awesome. work, @roedoejet. Feel free to PR any links you might have that are relevant, here, too.

**Comment by RichardLitt** [comment]
Hey @roedoejet - just checking in. How is FirstVoices going? Any new resources to add? If not, I am going to close this issue. :)

**Comment by roedoejet** [comment]
Hey @RichardLitt, everything is going well and the first batch of FV app rebuilds are public:

Halq'eméylem: www.waldayu.org/stolo 
Hlg̲aagilda X̲aayda Kil: www.waldayu.org/skidegate
Ktunaxa: www.waldayu.org/ktunaxa
Nisg̲a'a: www.waldayu.org/nisga
SENĆOŦEN: www.waldayu.org/sencoten
Ucwalmícwts: www.waldayu.org/lilwat

The Waldayu site however is going to be undergoing extensive changes in the next few months during which time another 9 FV apps should be published. These apps are in effect being made with what I'll be calling version 1.x which is all written in Ionic 1 (AngularJS). We already have our eye on, and are developing, a 2.x version which will incorporate automatic syncing from the FV database and added features (possibly QR stuff and/or stories etc). The 2.x version is being developed in Ionic 3/TypeScript/Angular 4 and is the version I'm writing documentation for and will be releasing under AGPLv3. I think it will be easier to have collaborators with an Ionic 3 codebase than an Ionic 1. I'll be sure to make a pull request when I have any relevant repos to share.

This is a long-winded way of saying you can probably close this issue for now :)

**Comment by RichardLitt** [comment]
Thank you! Awesome. Best of luck, and looking forward to having some repos added. :)
