### ISSUE TITLE
Make a logo for the project 

### ISSUE THREAD

**Issue by cesine** [RichardLitt/endangered-languages#80]
I want to invite some of my interns and other developers I know who are on github who build software for low resource languages. 

Lets make a logo for the project so that they wont be invited to a placeholder project

**Comment by cesine** [comment]
![low resource languages project logo](https://cloud.githubusercontent.com/assets/196199/9026558/fc3fb926-3900-11e5-9e00-16909dd4ea4f.png)

**Comment by cesine** [comment]
Now the project page looks like this if you are not a member of github

<img width="998" alt="screen shot 2015-08-02 at 10 45 21 am" src="https://cloud.githubusercontent.com/assets/196199/9026612/b04ae7ae-3903-11e5-9a9f-cc73a6d2446f.png">

**Comment by RichardLitt** [comment]
Looks great! Awesome, glad you did this.
