### ISSUE TITLE
Invite more collaborators who are already on GitHub

### ISSUE THREAD

**Issue by cesine** [RichardLitt/endangered-languages#81]
We'd like to welcome other githubers to join us on the [LowResourceLanguage](https://github.com/orgs/LowResourceLanguages/teams/contributors) project, I invited a few. 

If anyone else wants to join, let us know about you and send us a link to your github so we can see what you specialize in.

We don't really have any ground rules about who can join, but the important thing is to be friendly and supportive and help out when you can. Most of us have jobs and/or careers and/or studies and/or kids, so we can't be 100% available but the little bit we can do, will benefit the greater good!

After you have been invited, if you want your membership to be public, you can publish it like this:

<img width="1009" alt="screen shot 2015-08-02 at 10 42 14 am" src="https://cloud.githubusercontent.com/assets/196199/9026598/324acf68-3903-11e5-89e3-e470f913a5f7.png">

**Comment by cesine** [comment]
moved to https://github.com/LowResourceLanguages/about/issues/3

**Comment by RichardLitt** [comment]
Thanks!
