### ISSUE TITLE
See if any of the dictionaries were made on OSS http://wil.cdh.ucla.edu/yaqui/WIL:Indigenous_Language_Websites

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#9]

**Comment by RichardLitt** [comment]
Checked the A's - none of them are on open source software.

**Comment by HughP** [comment]
This one: http://www.capixabismo.com.br/tupi.htm I think is a Lexique Pro output. We had a few of these Lexique Pro outputs in our collection of South American Languages under the older SIL website.

**Comment by RichardLitt** [comment]
Lexique Pro and the resources provided by Freelang.net both appear to be freeware, but not open source. Not sure about including them.

**Comment by HughP** [comment]
Good point. I'll raise that question in my channels... see if we can't move Lexique pro to github.

**Comment by RichardLitt** [comment]
The list has changed. The new site: http://wil.cdh.ucla.edu/indigenous-language-websites

I think that this issue should be closed. Most of the links here are just to word lists, and half of the links are actually broken at the moment. Reopen if anyone finds anything.
