### ISSUE TITLE
Clone all SourceForge repositories into https://github.com/LowResourceLanguages/

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#91]
Current SourceForge projects:
- [accentuate.us](http://sourceforge.net/p/lingala/code/HEAD/tree/) a.k.a. "charlifter". Statistical Unicodification of plain text for many languages
- [AGTK](http://sourceforge.net/projects/agtk/) AGTK is a suite of software components for building tools for annotating linguistic signals, time-series data which documents any kind of linguistic behavior (e.g. audio, video). The internal data structures are based on annotation graphs.
- [Apertium](http://sourceforge.net/projects/apertium/) Apertium is a toolbox to build open-source shallow-transfer machine translation systems, especially suitable for related language pairs: it includes the engine, maintenance tools, and open linguistic data for several language pairs.
- [CTK](http://champollion.sourceforge.net/) Built around LDC's champollion sentence aligner kernel, Champollion Tool Kit (CTK) aims to providing ready-to-use parallel text sentence alignment tools for as many language pairs as possible.
- [Gramadóir](http://sourceforge.net/projects/gramadoir/) Grammar checking engine that is designed for the rapid development of grammar checkers for minority languages and other languages with limited computational resources.
- [hunspell.old](https://github.com/sillsdev/hunspell.old) Mirror of the Hunspell CVS repository at SourceForge (http://hunspell.cvs.sourceforge.net/hunspell)
- [Skype in your language](http://sourceforge.net/projects/skypeinyourlang/) Translate Skype into unsupported languages
- [Gargantua](http://sourceforge.net/projects/gargantua/) Fast Unsupervised Sentence Aligner described in "Improved unsupervised sentence alignment for symmetrical and asymmetrical parallel corpora", COLING 2010.
- [Bangla-অঙ্কুর for Mac](http://sourceforge.net/projects/onkur/) This project aims to develop a phonetic based Bangla typing system for Macintosh computer which can be developed into a transliteration technique in the future.
- [Bengali Writer](http://sourceforge.net/projects/bengaliwriter/) `Bengali Writer' is a set of utilities for computerized editing and typesetting in Bengali, a language of India and Bangladesh. It comprises a set of fonts for Bengali in several formats (METAFONT, BDF, PS), a text editor with spell-cheking, export, and more.
- [Ekushey](http://sourceforge.net/projects/ekushey/) Bangla Computing and Localization Project for the Bangla speaking people.
- [Lekho](http://sourceforge.net/projects/lekho/) A collection of tools and resources for using bangla on computers
- [Lingala NLP](http://sourceforge.net/projects/lingala/) NLP tools and resources for Lingala

**Comment by RichardLitt** [comment]
Here is a justification for not using SF: http://blog.gluster.org/2013/08/how-far-the-once-mighty-sourceforge-has-fallen/. Here is a [reddit thread about it, too](https://www.reddit.com/r/sysadmin/comments/1kxuul/beware_of_sourceforge_downloads_new_owner_is/). 

I contacted Phillip Cash about searching the ILAT archives to see if this has been done yet, but got no response. 

- [ ] Send a message to ILAT asking if anyone has done anything about SourceForge.

**Comment by cesine** [comment]
I have some time today to help out. 

I did the Lingala import, and then realized that `cos` is @kscanne on github. We found a script that can do import source forge issues if you export them from your admin dashboard TODO transfer lingala to @kscanne and ask @kscanne if he likes this idea... of if he prefers to keep the issues on sourceforge.
* https://github.com/cmungall/gosf2github

**Comment by kscanne** [comment]
FYI I moved all of my repos from sourceforge to github a couple of months ago.  Gramadóir in particular is now here: https://github.com/kscanne/gramadoir

The only exception was the lingala repository which is contains some massive data files that probably shouldn't be under version control anyway.   All of the import tools fail on it because of its size.  At some point in the future I'll create a new repo here with just the code and try to preserve as much of this history as possible.

**Comment by cesine** [comment]
@kscanne cool! i classified the repos into groups that are already on github. 

@RichardLitt i might not have time to finish this (there are still 2 more repos to go, with a ton of files that might need to be individually downloaded (?)) but i will at least prep a PR to update the links the github forks and maybe contact the maintainers to see if they want the repos in their own githubs now that we've tracked them down :)

**Comment by RichardLitt** [comment]
@cesine Sounds great! There's no rush, but thanks so much for taking the initiative on this.

**Comment by RichardLitt** [comment]
@cesine Should we consider this done?

**Comment by cesine** [comment]
hi :) 

there are still 2 more TODOs :( but we could make a new issue for them? or close this issue until we have time.

* Bangla-অঙ্কুর for Mac
* ekushey

**Comment by kghose** [comment]
@cesine  and @RichardLitt Thank you so much for doing all this work. I am happy to transfer ownership for Lekho! This project, however, is majorly obsolete - it was somewhat relevant when editor support for UTF-8 was poor, but now I think all major OSes have good Bengali support. It is a historical curiosity now.

**Comment by RichardLitt** [comment]
@kghose Nice to see you here! Transferring isn't necessary; if it's on GitHub, we can fork it, and if it isn't we can clone it and host it that way. You still retain copyright and storage. 

Obsolete doesn't mean not potentially useful. While Bengali is doing well, thousands of other languages aren't, and they may benefit from seeing how you helped build editor support.

**Comment by RichardLitt** [comment]
I think this can be closed. The work was good (thanks, @cesine), but I don't think we need to clone those two other repos at this time.
